_base_model: &base_model
    admin_roles: [ association-admin ]
    view_roles: [ association-auditor ]

roles:
    association-admin: Association administrator (full privileges over all associations)
    association-auditor: Associationt auditor (viewing privileges over all associations)

models:
    association:
        <<: *base_model
        base: organization
        extend: true
        display: "<name>"
        priority: 70
        fields:
            url:
                type: url
            type:
                type: string
            bio:
                type: text
            member_count:
                type: integer
            staff_count:
                type: integer
            year_founded:
                type: integer
            budget:
                type: string
